class Questions

	def boolean
		[{:question => "not False", :answer => "True"}, 
		 {:question => "not True", :answer => "False"},
		 {:question => "True or False", :answer => "True"},
		 {:question => "True or True", :answer => "True"},
		 {:question => "False or True", :answer => "True"},
		 {:question => "False or False", :answer => "False"},
		 {:question => "True and False", :answer => "False"},
		 {:question => "True and True", :answer => "True"},
		 {:question => "False and True", :answer => "False"},
		 {:question => "False and False", :answer => "False"},
		 {:question => "not (True or False)", :answer => "False"},
		 {:question => "not (True or True)", :answer => "False"},
		 {:question => "not (False or True)", :answer => "False"},
		 {:question => "not (False or False)", :answer => "True"},
		 {:question => "not (True and False)", :answer => "True"},
		 {:question => "not (True and True)", :answer => "False"},
		 {:question => "not (False and True)", :answer => "True"},
		 {:question => "not (False and False)", :answer => "True"},
		 {:question => "1 != 0", :answer => "True"},
		 {:question => "1 != 1", :answer => "False"},
		 {:question => "0 != 1", :answer => "True"},
		 {:question => "0 != 0", :answer => "False"},
		 {:question => "1 == 0", :answer => "False"},
		 {:question => "1 == 1", :answer => "True"},
		 {:question => "0 == 1", :answer => "False"},
		 {:question => "0 == 0", :answer => "True"}]
	end

	def capitals
		[ {:question => "Alabama", :answer => "Montgomery"},
			{:question => "Alaska", :answer => "Juneau"},
			{:question => "Arizona", :answer => "Phoenix"},
			{:question => "Arkansas", :answer => "Little Rock"},
			{:question => "California", :answer => "Sacramento"},
			{:question => "Colorado", :answer => "Denver"},
			{:question => "Connecticut", :answer => "Hartford"},
			{:question => "Delaware", :answer => "Dover"},
			{:question => "Florida", :answer => "Tallahassee"},
			{:question => "Georgia", :answer => "Atlanta"},
			{:question => "Hawaii", :answer => "Honolulu"},
			{:question => "Idaho", :answer => "Boise"},
			{:question => "Illinois", :answer => "Springfield"},
			{:question => "Indiana", :answer => "Indianapolis"},
			{:question => "Iowa", :answer => "Des Moines"},
			{:question => "Kansas", :answer => "Topeka"},
			{:question => "Kentucky", :answer => "Frankfort"},
			{:question => "Louisiana", :answer => "Baton Rouge"},
			{:question => "Maine", :answer => "Augusta"},
			{:question => "Maryland", :answer => "Annapolis"},
			{:question => "Massachusetts", :answer => "Boston"},
			{:question => "Michigan", :answer => "Lansing"},
			{:question => "Minnesota", :answer => "Saint Paul"},
			{:question => "Mississippi", :answer => "Jackson"},
			{:question => "Missouri", :answer => "Jefferson City"},
			{:question => "Montana", :answer => "Helena"},
			{:question => "Nebraska", :answer => "Lincoln"},
			{:question => "Nevada", :answer => "Carson City"},
			{:question => "New Hampshire", :answer => "Concord"},
			{:question => "New Jersey", :answer => "Trenton"},
			{:question => "New Mexico", :answer => "Santa Fe"},
			{:question => "New York", :answer => "Albany"},
			{:question => "North Carolina", :answer => "Raleigh"},
			{:question => "North Dakota", :answer => "Bismarck"},
			{:question => "Ohio", :answer => "Columbus"},
			{:question => "Oklahoma", :answer => "Oklahoma City"},
			{:question => "Oregon", :answer => "Salem"},
			{:question => "Pennsylvania", :answer => "Harrisburg"},
			{:question => "Rhode Island", :answer => "Providence"},
			{:question => "South Carolina", :answer => "Columbia"},
			{:question => "South Dakota", :answer => "Pierre"},
			{:question => "Tennessee", :answer => "Nashville"},
			{:question => "Texas", :answer => "Austin"},
			{:question => "Utah", :answer => "Salt Lake City"},
			{:question => "Vermont", :answer => "Montpelier"},
			{:question => "Virginia", :answer => "Richmond"},
			{:question => "Washington", :answer => "Olympia"},
			{:question => "West Virginia", :answer => "Charleston"},
			{:question => "Wisconsin", :answer => "Madison"},
			{:question => "Wyoming", :answer => "Cheyenne"}]
	end
end